services:
  nginx:
    image: nginx:latest
    container_name: gatewise-nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - backend
      - keycloak

    networks:
      - internal

    restart: always


  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: gatewise-keycloak

    command: start

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_URL: https://${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"

      KC_PROXY_HEADERS: xforwarded

      KC_HTTP_ENABLED: "true"

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      API_URL: ${API_URL}
      API_AUTH_KEY: ${API_AUTH_KEY}

    depends_on:
      - keycloak-db

    expose:
      - "8080"

    networks:
      - internal

    restart: always


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

    container_name: gatewise-backend
    restart: always

    environment:
      ConnectionStrings__DefaultConnection: "Host=gatewise-db;Database=${GATEWISE_DB_NAME};Username=${GATEWISE_DB_USER};Password=${GATEWISE_DB_PASSWORD}"

      JwtBearer__ValidIssuer: "https://${KC_HOSTNAME}/realms/master"

    depends_on:
      - gatewise-db
      - keycloak

    expose:
      - "5353"

    networks:
      - internal


  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gatewise-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    expose:
      - "5672"
      - "15672"

    networks:
      - internal

    restart: always


  keycloak-db:
    image: postgres:15
    container_name: gatewise-keycloak-db

    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}

    volumes:
      - kc_pgdata:/var/lib/postgresql/data

    networks:
      - internal

    restart: always


  gatewise-db:
    image: postgres:15
    container_name: gatewise-db

    environment:
      POSTGRES_DB: ${GATEWISE_DB_NAME}
      POSTGRES_USER: ${GATEWISE_DB_USER}
      POSTGRES_PASSWORD: ${GATEWISE_DB_PASSWORD}

    volumes:
      - gw_pgdata:/var/lib/postgresql/data

    networks:
      - internal

    restart: always


networks:
  internal:
    driver: bridge


volumes:
  kc_pgdata:
  gw_pgdata: