services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      API_URL: ${API_URL}
      API_AUTH_KEY: ${API_AUTH_KEY}
      GATEWISE_DB_HOST: gatewise-db
      GATEWISE_DB_PORT: "5432"
      GATEWISE_DB_NAME: ${GATEWISE_DB_NAME}
      GATEWISE_DB_USER: ${GATEWISE_DB_USER}
      GATEWISE_DB_PASSWORD: ${GATEWISE_DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE: user.login.sync
    volumes:
      - ../keycloak/providers:/opt/keycloak/providers:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - internal

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app/GateWise.Api
    command: dotnet watch run --urls=http://0.0.0.0:5353
    volumes:
      - ../backend:/app
    ports:
      - "5353:5353"
    environment:
      ConnectionStrings__DefaultConnection: "Host=gatewise-db;Database=${GATEWISE_DB_NAME};Username=${GATEWISE_DB_USER};Password=${GATEWISE_DB_PASSWORD}"
      JwtBearer__Authority: "http://localhost:8080/realms/master"
      JwtBearer__ValidIssuer: "http://localhost:8080/realms/master"
      JwtBearer__JwksUri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      JwtBearer__RequireHttpsMetadata: "false"
    depends_on:
      - gatewise-db
      - keycloak
    networks:
      - internal

  consumer:
    build:
      context: ../sync-user-events-message-queue
    environment:
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672"
      DATABASE_URL: "postgres://${GATEWISE_DB_USER}:${GATEWISE_DB_PASSWORD}@gatewise-db:5432/${GATEWISE_DB_NAME}"
      QUEUE_NAME: user.login.sync
      DLQ_NAME: user.login.sync.dlq
    depends_on:
      - rabbitmq
      - gatewise-db
    networks:
      - internal

networks:
  internal:
    driver: bridge