services:
  keycloak:
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_NAME: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: https://3kb5qjd2-8080.brs.devtunnels.ms   
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_PROXY: xforwarded
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/themes:/opt/keycloak/themes

  gatewise-db:
    image: postgres:15
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: gatewise
      POSTGRES_USER: gatewise
      POSTGRES_PASSWORD: gatewise
    volumes:
      - ../backend/data/gatewise:/var/lib/postgresql/data

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app/GateWise.Api
    command: dotnet watch run --urls=http://0.0.0.0:5353
    volumes:
      - ../backend/GateWise.Api:/app/GateWise.Api
      - ../backend/GateWise.Core:/app/GateWise.Core
      - ../backend/GateWise.Infrastructure:/app/GateWise.Infrastructure
      - ../backend/GateWise.Api/Keys:/app/GateWise.Api/Keys
    ports:
      - "5353:5353"
    environment:
      ConnectionStrings__DefaultConnection: "Host=gatewise-db;Database=gatewise;Username=gatewise;Password=gatewise"
    depends_on:
    - gatewise-db
    - keycloak

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  consumer:
    build:
      context: ../sync-user-events-message-queue
    env_file:
      - ../sync-user-events-message-queue/.env
    depends_on:
      - rabbitmq
      - gatewise-db

  outbox-worker:
    build:
      context: ../event-sync-outbox-worker
    env_file:
      - ../event-sync-outbox-worker/.env
    depends_on:
      - gatewise-db
      - rabbitmq

  maven-builder:
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ../spiprovider/university-idp:/app
      - ../keycloak/providers:/output
    command: >
      bash -c "
        mvn clean package &&
        cp target/*.jar /output
      "
volumes:
  rabbitmq_data: