version: '3.9'

services:
  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc_pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: https://3kb5qjd2-8080.brs.devtunnels.ms  
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_PROXY: xforwarded
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - kc_data:/opt/keycloak/data
      - ../keycloak/providers:/opt/keycloak/providers

volumes:
  kc_pgdata:
  kc_data:
