version: "3.9"

services:
  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
    networks:
      - internal

  gatewise-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${GATEWISE_DB_NAME}
      POSTGRES_USER: ${GATEWISE_DB_USER}
      POSTGRES_PASSWORD: ${GATEWISE_DB_PASSWORD}
    volumes:
      - gatewise_pgdata:/var/lib/postgresql/data
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal

volumes:
  kc_pgdata:
  gatewise_pgdata:
  rabbitmq_data:

networks:
  internal:
    driver: bridge