server {
    listen 80;
    server_name auth.gatewiseiot.com;

    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name gatewiseiot.com www.gatewiseiot.com;

    location = /health {
        access_log off;

        add_header Content-Type text/plain;

        return 200 "OK";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80 default_server;
    server_name _;

    return 444;
}