server {
    listen 443 ssl;
    server_name auth.gatewiseiot.com;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/auth-security.conf;

    location / {
        proxy_pass http://keycloak;

        include /etc/nginx/snippets/proxy.conf;

        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
    }
}

server {
    listen 443 ssl;
    server_name gatewiseiot.com www.gatewiseiot.com;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security.conf;

    location = /health {
        access_log off;

        add_header Content-Type text/plain;

        return 200 "OK";
    }

    location / {
        proxy_pass http://backend;

        include /etc/nginx/snippets/proxy.conf;
    }
}

server {
    listen 443 ssl default_server;
    server_name _;

    include /etc/nginx/snippets/ssl.conf;

    return 444;
}